services:
  # Static Site
  - type: web
    name: piewallah
    env: static
    rootDir: .
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - source: /api/(.*)
        destination: /api/$1
        type: redirect
      - source: /assets/(.*)
        destination: /assets/$1
        type: redirect
      - source: /(.*)$
        destination: /index.html
        type: rewrite
    envVars:
      - key: NODE_VERSION
        value: 18
